### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by ghost** [carsenk/denariusnodewallet#4]
Im having this error when i run nodemon app.js or node app.js 

root@gitian-VirtualBox:/home/gitian/denariusnodewallet# nodemon app.js [nodemon] 1.12.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
(node:19037) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
✓ Denarius Wallet is running at http://localhost:3000 in development mode
  Press CTRL-C to stop

/home/gitian/denariusnodewallet/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/gitian/denariusnodewallet/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:159:13)
    at Connection.<anonymous> (/home/gitian/denariusnodewallet/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:254:19)
    at Connection.emit (events.js:159:13)
    at Socket.<anonymous> (/home/gitian/denariusnodewallet/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:254:19)
    at Socket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[nodemon] app crashed - waiting for file changes before starting...

any idea how to fix this?

**Comment by enkayz** [comment]
make sure your mongodb is running and accepting connections on localhost:27017
